import Header from "@/layouts/Header";
import "./globals.css";
import { montserrat } from "@/libs/font";
import FakeLoading from "@/components/FakeLoading";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr">
			<body className={montserrat.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
